export const Data = [
  {key:'1', value:'Amazonas'},
  {key:'2', value:'Antioquia'},
  {key:'3', value:'Arauca'},
  {key:'4', value:'Archipiélago de San Andrés'},
  {key:'5', value:'Atlántico'},
  {key:'6', value:'Bogotá D.C.'},
  {key:'7', value:'Bolívar'},
  {key:'8', value:'Boyacá'},
  {key:'9', value:'Caldas'},
  {key:'10', value:'Caquetá'},
  {key:'11', value:'Casanare'},
  {key:'12', value:'Cauca'},
  {key:'13', value:'Cesar'},
  {key:'14', value:'Chocó'},
  {key:'15', value:'Córdoba'},
  {key:'16', value:'Cundinamarca'},
  {key:'17', value:'Guainía'},
  {key:'18', value:'Guaviare'},
  {key:'19', value:'Huila'},
  {key:'20', value:'La Guajira'},
  {key:'21', value:'Magdalena'},
  {key:'22', value:'Meta'},
  {key:'23', value:'Nariño'},
  {key:'24', value:'Norte de Santander'},
  {key:'25', value:'Putumayo'},
  {key:'26', value:'Quindío'},
  {key:'27', value:'Risaralda'},
  {key:'28', value:'Santander'},
  {key:'29', value:'Sucre'},
  {key:'30', value:'Tolima'},
  {key:'31', value:'Valle del Cauca'},
  {key:'32', value:'Vaupés'},
  {key:'33', value:'Vichada'},

]